CREATE TABLE "public"."garage" (
    "id" SERIAL,
    "user_id" integer NOT NULL,
    "slot_name" text NOT NULL,

    "character_class" text NOT NULL,
    "growth" text NOT NULL,
    "hunger" text NOT NULL,
    "thirst" text NOT NULL,
    "stamina" text NOT NULL,
    "health" text NOT NULL,
    "bleeding_rate" text NOT NULL,
    "oxygen" text NOT NULL,
    "sex" boolean NOT NULL,
    "is_resting" boolean NOT NULL,
    "broken_legs" boolean NOT NULL,
    "progression_points" text NOT NULL,
    "progression_tier" text NOT NULL,
    "unlocked_characters" text NOT NULL,
    "location_thenyaw_island" text,
    "rotation_thenyaw_island" text,
    "location_isle_v3" text,
    "rotation_isle_v3" text,
    "camera_rotation_thenyaw_island" text,
    "camera_distance_thenyaw_island" text,
    "camera_rotation_isle_v3" text,
    "camera_distance_isle_v3" text,
    "skin_palette_variation" text NOT NULL,
    "skin_palette_section1" integer NOT NULL,
    "skin_palette_section2" integer NOT NULL,
    "skin_palette_section3" integer NOT NULL,
    "skin_palette_section4" integer NOT NULL,
    "skin_palette_section5" integer NOT NULl,
    "skin_palette_section6" integer NOT NULL,
    
    PRIMARY KEY ("id"),
    FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE
);
