use diesel::prelude::*;
use chrono::prelude::*;

#[derive(Queryable)]
pub struct GarageSlot {
  pub id: u64,
  pub user_id: u64,
  pub character_class: String,
  pub dna: String,
  pub growth: String,
  pub hunger: String,
  pub thirst: String,
  pub stamina: String,
  pub health: String,
  pub bleeding_rate: String,
  pub oxygen: String,
  pub sex: bool,
  pub is_resting: bool,
  pub broken_legs: bool,
  pub progression_points: String,
  pub progression_tier: String,
  pub unlocked_characters: String,
  pub location_thenyaw_island: Option<String>,
  pub rotation_thenyaw_island: Option<String>,
  pub location_isle_v3: Option<String>,
  pub rotation_isle_v3: Option<String>,
  pub camera_rotation_thenyaw_island: Option<String>,
  pub camera_distance_thenyaw_island: Option<String>,
  pub camera_rotation_isle_v3: Option<String>,
  pub camera_distance_isle_v3: Option<String>,
  pub skin_palette_section1: i32,
  pub skin_palette_section2: i32,
  pub skin_palette_section3: i32,
  pub skin_palette_section4: i32,
  pub skin_palette_section5: i32,
  pub skin_palette_section6: i32,
  pub skin_palette_variation: String,
}

// #[derive(Insertable)]
// #[table_name="garage"]
pub struct GarageSlotInsertable<'a> {
  pub character_class: &'a String,
  pub dna: &'a String,
  pub growth: &'a String,
  pub hunger: &'a String,
  pub thirst: &'a String,
  pub stamina: &'a String,
  pub health: &'a String,
  pub bleeding_rate: &'a String,
  pub oxygen: &'a String,
  pub sex: bool,
  pub is_resting: bool,
  pub broken_legs: bool,
  pub progression_points: &'a String,
  pub progression_tier: &'a String,
  pub unlocked_characters: &'a String,
  pub location_thenyaw_island: Option<&'a String>,
  pub rotation_thenyaw_island: Option<&'a String>,
  pub location_isle_v3: Option<&'a String>,
  pub rotation_isle_v3: Option<&'a String>,
  pub camera_rotation_thenyaw_island: Option<&'a String>,
  pub camera_distance_thenyaw_island: Option<&'a String>,
  pub camera_rotation_isle_v3: Option<&'a String>,
  pub camera_distance_isle_v3: Option<&'a String>,
  pub skin_palette_section1: i32,
  pub skin_palette_section2: i32,
  pub skin_palette_section3: i32,
  pub skin_palette_section4: i32,
  pub skin_palette_section5: i32,
  pub skin_palette_section6: i32,
  pub skin_palette_variation: &'a String,
}
